jobs:
  main:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./ci/main

name: Run

on:
  schedule:
    - cron: "15 2/3 * * *"
